fixed help menu bug

diff --git a/autogit b/autogit
--- a/autogit
+++ b/autogit
@@ -9,7 +9,7 @@ FOLDER_NAME=""
 # Function to display help menu and exit
 help_menu() {
   echo "
-Welcome to autogit. This script automatically inits and pushes a GitHub repo. All options are optional. If you just run `autogit` by itself, it will init and push a git repo with the current folder name, and the default branch name, using your set GitHub username
+Welcome to autogit. This script automatically inits and pushes a GitHub repo. All options are optional. If you just run 'autogit' by itself, it will init and push a git repo with the current folder name, and the default branch name, using your set GitHub username
 
   -f <folder_name>: Create a new folder with the specified name and initialize the Git repository inside it.
   -u <github_username>: Set the GitHub username for the remote repository.
@@ -17,13 +17,12 @@ Welcome to autogit. This script automatically inits and pushes a GitHub repo. Al
   -b <branch_name>: Set the initial branch name (default: 'main').
   -h: Displays this help menu
   "
-  exit 0
 }
 
 # Parse options
 while getopts ":f:u:r:b:h" opt; do
   case $opt in
-    h) help_menu; exit 0;;
+    h) help_menu; exit 1;;
     f) FOLDER_NAME="$OPTARG";;
     u) GITHUB_USERNAME="$OPTARG"; git config --global autogit.username "$GITHUB_USERNAME";;
     r) REPO_NAME="$OPTARG";;
@@ -32,11 +31,6 @@ while getopts ":f:u:r:b:h" opt; do
   esac
 done
 shift $((OPTIND-1))
-
-# If no arguments are left, exit
-if [ $# -eq 0 ]; then
-  exit 0
-fi
 
 # Create a new folder if specified
 if [ -n "$FOLDER_NAME" ]; then
@@ -50,18 +44,16 @@ if [ -z "$REPO_NAME" ]; then
 fi
 
 
-# Create the repository
-if [ $# -eq 0 ]; then
-  if [ -d ".git" ]; then
-    echo "Error: Current directory is already a Git repository."
-    exit 1
-  fi
-
-  echo "# $REPO_NAME" >> README.md
-  git init
-  git add README.md
-  git commit -m "first commit"
-  git branch -M "$BRANCH_NAME"
-  git remote add origin "git@github.com:$GITHUB_USERNAME/$REPO_NAME.git"
-  git push -u origin "$BRANCH_NAME"
+if [ -d ".git" ]; then
+  echo "Error: Current directory is already a Git repository."
+  exit 1
 fi
+
+# Create the repository
+echo "# $REPO_NAME" >> README.md
+git init
+git add README.md
+git commit -m "first commit"
+git branch -M "$BRANCH_NAME"
+git remote add origin "git@github.com:$GITHUB_USERNAME/$REPO_NAME.git"
+git push -u origin "$BRANCH_NAME"
